services:
  db:
    image: postgres:15-alpine
    container_name: postgres_aula
    restart: always
    environment:
      POSTGRES_USER:  vic
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teste_db
    ports:
      - "6123:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_aula
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6124:80"
    depends_on:
      - db

volumes:
  pgdata: